.gitignore

Small correction to gitignore to exclude the compiled binary but not `lib/kion/*`.

Ignore compiled kion binary at project root

---

lib/kion/account.go
lib/kion/auth.go
lib/kion/car.go
lib/kion/console.go
lib/kion/kion.go
lib/kion/private.go
lib/kion/project.go
lib/kion/stak.go
main.go

This checks for a 403 when querying for accounts as part of STAK generation. If a 403 is received it tries to use a private API endpoint that can provide a list of CARs with associated accounts for a given project.
Closes #7

Add workaround for users with min project permissions

---

.github/workflows/golang-test.yml
.github/workflows/golangci-lint.yml
lib/helper/helper.go
lib/helper/helper_test.go
main.go

Initial stub out of a unit test and test action.

Add test for printing of STAKs

---

lib/helper/helper.go

**Problem Description:**  
Users experienced an "unexpected EOF while looking for matching `\"` error when initiating a bash subshell. This was due to improperly escaped quotes in the command string for sourcing the user's `.bashrc` file and setting the `PS1` variable.
**Solution:**  
The fix corrects the command string's escape mechanism for quotes around `$HOME/.bashrc`. Proper escaping ensures that the shell interprets the entire command correctly, thereby preventing the EOF error.

Fix "unexpected EOF" Error in Bash Subshell Command

---

README.md
lib/kion/car.go
main.go

This PR addresses an issue where the application defaulted to opening a browser URL associated with the first cloud access role (CAR) in the list, ignoring the user's favorite account selection for web access type favorites. The core of the problem was the `GetCARByName` function, which did not consider the account number when fetching a CAR, leading to incorrect CAR selection.
- I introduced a new function, `GetCARByNameAndAccount,` that accurately filters CARs by both their name and the account number, ensuring the correct CAR is selected based on the user's favorite account.
- Modified the `favorites` function to use this new function when handling web access type favorites, thereby fetching the correct CAR and generating the appropriate federation URL.
- Manual testing was conducted …

Fix CAR Selection Logic for Web Access Type Favorites

---

lib/kion/car.go
main.go

Attempt to find an exact matching CAR first, if none found fall back to the first match by name only. This workaround is in place due to limitations of the Kion api in returning a full list of CARs for users with minimal project permissions.

Update logic on car lookup for web federation

---

main.go

This PR introduces a user-friendly message that enhances the feedback provided when selecting a favorite with `access_type` set to `web`. This message informs the user about the account name, account number, and the AWS IAM role name being accessed, providing a clearer understanding of the federating process.
- Added a `fmt.Printf` statement to display the federating account's name, account number, and AWS IAM role name before opening the browser for web access type favorites.
- Manual tests were conducted to ensure the message correctly displays the intended information.
- Verified that the browser opens as expected and the federating process proceeds without any issues.

Feature: Enhance User Feedback for Web Access Type Favorites

---

lib/kion/saml.go

Chrome 123 added [private network access checks](https://developer.chrome.com/blog/chrome-123-beta#private_network_access_checks_for_navigation_requests_warning-only_mode) via a pre-flight OPTIONS request.  
This PR updates the callback server to respond 200, but otherwise ignore OPTIONS checks.

Fix SAML auth to work with private network access checks

---

CHANGELOG.md
README.md
go.mod
lib/helper/helper.go
lib/kion/account.go
lib/kion/car.go
main.go

Allows users to pass `--account [number]` and ~~or~~ `--car [name]` to bypass prompts when generating short term access keys / starting sessions. Helpful to allow fully headless operation without having to setup favorites.

Add subcommand flags

---

CHANGELOG.md
README.md
lib/helper/helper.go
lib/helper/helper_test.go
lib/structs/structs.go
main.go

Users can set a region on their favorites or pass a region via a flag. Will conditionally set AWS_REGION as needed. Also works with stak gen when printing.
Closes: #3

Add initial region support for run & stak commands

---

.golangci.yml
CHANGELOG.md
README.md
lib/helper/helper.go
main.go

Adds commands to mirror usage and functionality of the older `ctkey` utility. Allows customers to drop in the new kion-cli with minimal reconfiguration.

Add compatibility commands for ctkey

---

CHANGELOG.md
README.md
lib/helper/helper.go

This PR adds browser agent detection and if in Firefox handles AWS console session logout via tabs vs iframes.
Closes #29

Workaround Firefox limitations for AWS logouts

---

CHANGELOG.md
lib/helper/browser.go
main.go

This PR utilizes the `redirect_uri` query parameter to handle closing out existing AWS web console sessions then automatically redirecting to the new federated session. This bypasses the need for logging out via iframes or tab manipulation via javascript. Thanks @sculliga for the intel!
Closes #35

Update console federation flow

---

CHANGELOG.md
README.md
lib/cache/cache.go
lib/cache/helpers-cache.go
lib/cache/session-cache.go
lib/kion/kion.go
lib/structs/configuraton-structs.go
main.go

Allow users to point to another Kion CLI configuration file by setting the `KION_CONFIG` environment variable. Also add support for defining profiles within the configuration file. When setting a profile, any additionally passed flags will override any settings within the selected profile to maintain precedence `Flag > Environment Variable > Configuration File > Default Value`.
Closes #41

Add config file override and profiles support

---

main.go

Updating 99designs/keyring config for Gnome Wallet (libsecret) to use default keyring instead of creating a new one for kion-cli

kion-cli doesn't use default keyring on Gnome Wallet (libsecret)

---

README.md
lib/cache/cache.go
lib/cache/password-cache.go
main.go

This PR provides a way to have login passwords stored in encrypted storage (eg the system keyring) rather than the current options of 
a) re-typing them when establishing each new session, or 
b) stashing them in plaintext in .kion.yml (or env vars which are typically populated from plaintext scripts)

Adding encrypted storage for login passwords

---

Makefile

- `build-windows` target to the Makefile for building the Kion CLI binary for Windows (GOOS=windows, GOARCH=amd64).
- `LDFLAGS` variable in the Makefile to streamline build flag settings, including binary compression and version information.
- Added cleaning of the `kion_windows.exe` binary in the `clean` target.
- Refactored the existing `build` target using the `LDFLAGS` variable to set version and compression flags.

Add Windows Build Support and Refactor Build Process

---

main.go

Exit with a non-zero exit code if an error bubbles up.
Resolves #63

Exit non-zero if error is present, resolves #63

---

lib/kion/saml.go

Fixes #81 
Moves to OS native methods for opening web links to support user preferences. Adds a timeout to the server listening for the SAML callback (60 seconds). Refactor to dry up the code and reduce cyclomatic complexity of functions.

Widen browser support for SAML authentication

---

README.md
lib/kion/saml.go
lib/structs/configuraton-structs.go
main.go

Fixes #71
Adds flag, env var, and config option to print SAML the authentication URL instead of automatically opening it in the users default browser.

Add option to print saml auth url

---

lib/cache/cache.go
lib/cache/helpers-cache.go
lib/cache/session-cache.go
lib/commands/commands.go

This should resolve #89. Even with the cache disabled, we're trying to initialize the keyring.
- This adds a NullKeyRing implementation
- Removes keyring access from some NullCache session functions.

Updating disable cache flag to also disable for login sessions

---

CHANGELOG.md
README.md
doc/config_sop.md
doc/man1/kion.1
lib/commands/commands.go
lib/commands/console.go
lib/commands/stak.go
lib/defaults/defaults.yml
lib/helper/output.go
lib/structs/configuraton-structs.go
main.go

This PR adds additional output to the `console` and `stak` commands to show users how to store their selection as a favorite. There is also a new quiet configuration option that will prevent these messages which are on by defualt.
Addresses the discussion: https://github.com/kionsoftware/kion-cli/discussions/91

Add favorite helper text and quiet flag

---

.github/workflows/golang-test.yml
.github/workflows/golangci-lint.yml
.golangci.yml
go.mod
go.sum

Upgrading go and golang-ci-lint to latest versions.

Bump version of go from 1.22 to 1.24.4
